### ISSUE TITLE
NullInjectorError when I try to mask on CustomElement

### ISSUE THREAD

**Issue by abeppler** [JsDaddy/ngx-mask#1038]
### Description

✍️ - I'm trying to create a mask in a Custom Element in Angular for an application in Blazor, when I run the application on the Angular server everything works, but on the Blazor server I get a NullInjectorError message.

## 🔥 Exception or Error

<pre><code>

ERROR NullInjectorError: R3InjectorError(xe)[Je -> Je -> Je]: 
  NullInjectorError: No provider for Je!
    at e.value (vendor.js:1:693726)
    at e.value (vendor.js:1:695645)
    at e.value (vendor.js:1:695645)
    at e.value (vendor.js:1:695645)
    at i.value (vendor.js:1:727330)
    at Object.get (vendor.js:1:723758)
    at $a (vendor.js:1:658854)
    at pr (vendor.js:1:659596)
    at Object.gl (vendor.js:1:702989)
    at He.ɵfac (vendor.js:1:420267)

</code></pre>

## 🌍 Your Environment

**My Module Class**
<pre><code>
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SharedModule } from '../shared.module';
import { CompanyManagementRoutingModule } from './company-management-routing.module';
import { CompanyManagementComponent } from './company-management.component';
import { CompanyEditComponent } from './company-edit/company-edit.component';
import { IConfig, NgxMaskModule } from 'ngx-mask';

export const options: Partial<IConfig> | (() => Partial<IConfig>) = null;

@NgModule({
    imports: [
        CommonModule,
        NgxMaskModule.forRoot(options),
        CompanyManagementRoutingModule,
        SharedModule
    ],
    declarations: [CompanyManagementComponent, CompanyEditComponent],
    entryComponents: [CompanyEditComponent],
})
export class CompanyManagementModule { }
</code></pre>

**Angular Version:**

<pre><code>
Angular CLI: 13.3.9
Node: 16.13.0
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13.3.11
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cdk                    13.3.9
@angular/cli                    13.3.9
@angular/elements               14.2.0
@angular/pwa                    13.3.9
@schematics/angular             13.3.9
rxjs                            7.5.6
typescript                      4.6.4
</code></pre>

**Comment by NepipenkoIgor** [comment]
@abeppler  Could you provide stackblitz or another environment ?

**Comment by andriikamaldinov1** [comment]
@abeppler close, becouse no activity in issue. If you will be have problem at future please create new issue with teamplate and stackblitz example.
