### ISSUE TITLE
Error in Module

### ISSUE THREAD

**Issue by rodalonts** [JsDaddy/ngx-mask#41]
Hello everyone,

I want to implement this component, I imported it into my ngModule as follows:

...
import { NgxMaskModule } from 'ngx-mask';
...

@NgModule({
    providers: [
      ...
    ],
    declarations: [
      ...  
    ],
    imports: [
       ...
        NgxMaskModule.forRoot(),
        ...
    ],
 ...
})

but when I run the project the following error occurs:

An unhandled exception occurred while processing the request.

NodeInvocationException: Document is not defined
ReferenceError: Document is not defined
at MaskService.ctorParameters (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\main-server.js:45113:17)
at ReflectionCapabilities.module.exports.ReflectionCapabilities._ownParameters (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:12474:93)
at ReflectionCapabilities.module.exports.ReflectionCapabilities.parameters (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:12504:48)
at JitReflector.module.exports.JitReflector.parameters (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:62880:44)
at CompileMetadataResolver.module.exports.CompileMetadataResolver._getDependenciesMetadata (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:51185:71)
at CompileMetadataResolver.module.exports.CompileMetadataResolver._getTypeMetadata (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:51110:26)
at CompileMetadataResolver.module.exports.CompileMetadataResolver._getInjectableMetadata (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:51096:21)
at CompileMetadataResolver.module.exports.CompileMetadataResolver.getProviderMetadata (F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:51387:40)
at F:\xxxxxxxxxxx\NetCore\ooooooooooo\ClientApp\dist\vendor.js:51316:49
at Array.forEach (<anonymous>)

Please help

**Comment by LimarenkoDenis** [comment]
@rodalonts could you provide package.json please

**Comment by rodalonts** [comment]
@LimarenkoDenis , this is my package.json. Thanks

{
  "name": "bbbbbbb",
  "private": true,
  "version": "0.0.0",
  "scripts": {
    "test": "karma start ClientApp/test/karma.conf.js"
  },
  "dependencies": {
    "@angular/animations": "~4.3.3",
    "@angular/common": "~4.3.3",
    "@angular/compiler": "~4.3.3",
    "@angular/compiler-cli": "~4.3.3",
    "@angular/core": "~4.3.3",
    "@angular/forms": "~4.3.3",
    "@angular/http": "~4.3.3",
    "@angular/platform-browser": "~4.3.3",
    "@angular/platform-browser-dynamic": "~4.3.3",
    "@angular/platform-server": "~4.3.3",
    "@angular/router": "~4.3.3",
    "@ngtools/webpack": "1.5.0",
    "@types/webpack-env": "1.13.0",
    "angular2-bootstrap-switch": "^0.2.3",
    "angular2-template-loader": "0.6.2",
    "aspnet-prerendering": "^3.0.1",
    "aspnet-webpack": "^2.0.1",
    "awesome-typescript-loader": "3.2.1",
    "bootstrap": "3.3.7",
    "css": "2.2.1",
    "css-loader": "0.28.4",
    "es6-shim": "0.35.3",
    "event-source-polyfill": "0.0.9",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "2.1.2",
    "file-loader": "0.11.2",
    "html-loader": "0.4.5",
    "install": "^0.10.1",
    "isomorphic-fetch": "2.2.1",
    "jquery": "3.2.1",
    "json-loader": "0.5.4",
    "lodash": "^4.17.4",
    "ng2-completer": "^1.6.3",
    "ng2-smart-table": "^1.2.2",
    "ngx-bootstrap": "1.9.3",
    "ngx-mask": "^2.0.3",
    "npm": "^5.4.2",
    "preboot": "4.5.2",
    "raw-loader": "0.5.1",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.4.2",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "traceur": "0.0.111",
    "typescript": "2.4.1",
    "url-loader": "0.5.9",
    "webpack": "^2.5.1",
    "webpack-hot-middleware": "2.18.2",
    "webpack-merge": "4.1.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "chai": "4.0.2",
    "jasmine-core": "2.6.4",
    "karma": "1.7.0",
    "karma-chai": "0.1.0",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-webpack": "2.0.3"
  }
}

**Comment by NepipenkoIgor** [comment]
@rodalonts Сould you try latest version and give feedback?
