### ISSUE TITLE
Metadata version mismatch for module

### ISSUE THREAD

**Issue by ertle** [JsDaddy/ngx-mask#55]
**Error:** Metadata version mismatch for module C:/inetpub/wwwroot/ngx-workspace/client-code/e-dog/node_modules/ngx-mask/build/config.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler\bundles\compiler.umd.js:25616:34)
    at StaticSymbolResolver._createSymbolsOf (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler\bundles\compiler.umd.js:25404:46)
    at StaticSymbolResolver.getSymbolsOf (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:14)
    at C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler\bundles\compiler.umd.js:24241:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler\bundles\compiler.umd.js:24240:79)
    at AotCompiler.analyzeModulesAsync (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler\bundles\compiler.umd.js:23796:47)
    at CodeGenerator.codegen (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at codegen (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\compiler-cli\src\main.js:13:81)
    at Object.main (C:\inetpub\wwwroot\ngx-workspace\client-code\e-dog\node_modules\@angular\tsc-wrapped\src\main.js:106:16)
Compilation failed
error Command failed with exit code 1.

**And my package.json:**

```
 "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/cdk": "^2.0.0-beta.12",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/material": "^2.0.0-beta.12",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/platform-server": "4.4.6",
    "@angular/router": "4.4.6",
    "@ngrx/effects": "^4.0.0",
    "@ngrx/router-store": "^4.0.0",
    "@ngrx/store": "^4.0.0",
    "@ngrx/store-devtools": "^4.0.0",
    "core-js": "2.4.1",
    "intl": "1.1.0",
    "ngx-cookie": "^1.0.0",
    "ngx-mask": "^2.1.17",
    "pikaday": "^1.6.1",
    "reflect-metadata": "0.1.8",
    "rxjs": "~5.4.2",
    "underscore": "^1.8.3",
    "zone.js": "^0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.4.6",
    "@types/pikaday": "^1.6.3",
    "@types/requirejs": "2.1.28",
    "@types/underscore": "^1.8.3",
    "angular2-router-loader": "0.3.5",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.2.3",
    "compression-webpack-plugin": "0.3.1",
    "copy-webpack-plugin": "^4.1.1",
    "css-loader": "0.28.7",
    "extract-text-webpack-plugin": "3.0.1",
    "file-loader": "1.1.4",
    "html-minify-loader": "1.3.0",
    "raw-loader": "0.5.1",
    "rimraf": "2.5.4",
    "style-loader": "0.19.0",
    "typescript": "~2.4.1",
    "webpack": "3.6.0"
  },
```

**Comment by NepipenkoIgor** [comment]
@ertle we will check

**Comment by PavelGonzales** [comment]
I have same error

**Comment by aditya-dikonia** [comment]
Facing same issue... Is there any solution?

**Comment by aditya-dikonia** [comment]
I have fixed this issue by downgrading the ngx-mask version by 1.0.3, npm install ngx-mask@1.0.3

**Comment by NepipenkoIgor** [comment]
@aditya-dikonia @PavelGonzales Could you try latest version

**Comment by kshaaban-** [comment]
Just tried latest, issue still exists
