### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length') in setUpControl

### ISSUE THREAD

**Issue by modul8com** [JsDaddy/ngx-mask#971]
# 🐞 bug report

### Is this a regression?
no

### Description
I have this mask on an input type="text"-field: mask="000.000.000||0000.000.000", but also on the input there's a 2 way binding like this: [(ngModel)]="myvariableInCode"...
I guess that this triggers an evaluation of the mask, and that's why I have the following error:

`Uncaught (in promise): TypeError: Cannot read properties of null (reading 'length') TypeError: Cannot read properties of null (reading 'length') at http://localhost:4200/vendor.js:233121:76 at Array.some (<anonymous>) at MaskDirective._setMask (http://localhost:4200/vendor.js:233120:39) at MaskDirective.<anonymous> (http://localhost:4200/vendor.js:233031:18) at Generator.next (<anonymous>) at http://localhost:4200/vendor.js:196779:71 at new ZoneAwarePromise (http://localhost:4200/polyfills.js:15796:33) at __awaiter (http://localhost:4200/vendor.js:196775:12) at MaskDirective.writeValue (http://localhost:4200/vendor.js:233015:71) at setUpControl (http://localhost:4200/vendor.js:40320:23)
`

In your code it's this line in the setUpControl method:

`dir.valueAccessor.writeValue(control.value);`

I guess control.value is undefined or null, which is why it fails... maybe you should put:

```
if (control && control.value) {
    dir.valueAccessor.writeValue(control.value);
}
```

## 🌍 Your Environment

**Angular Version:**

<pre><code>

@angular-devkit/architect       0.1102.18
@angular-devkit/build-angular   0.1102.18
@angular-devkit/core            11.2.18
@angular-devkit/schematics      11.2.18
@angular/cdk                    11.2.13
@angular/cli                    11.2.18
@angular/material               11.2.13
@schematics/angular             11.2.18
@schematics/update              0.1102.18
ng-packagr                      11.2.4
rxjs                            6.6.7
typescript                      4.1.6

</code></pre>

**Comment by modul8com** [comment]
fixed in later versions
